### ISSUE TITLE
Morning peer to peer code review.

### ISSUE THREAD

**Issue by koomekevo** [thecodechaser/Disney-characters-webapp#37]
## Hi Ranjeet

:heavy_check_mark: Your code is clean.
:heavy_check_mark: Your code adheres to ES6.

You can proceed to add styles :paintbrush: 

Happy coding :computer:

**Comment by thecodechaser** [comment]
> ## Hi Ranjeet
> ✔️ Your code is clean. ✔️ Your code adheres to ES6.
> 
> You can proceed to add styles 🖌️
> 
> Happy coding 💻

Hello @koomekevo 👋 
Thank you bro for your feedback, And I will definitely work on styles now
