### ISSUE TITLE
Morning session review

### ISSUE THREAD

**Issue by Ewoskyx** [thecodechaser/Disney-characters-webapp#43]
Hello Guys,
Congratulations on completing the project. Everything looks perfect. 🚀 
There is nothing to say 😃 
Cheers,

**Comment by roshan-bajgain** [comment]
Thank you man 🥇

**Comment by thecodechaser** [comment]
> Hello Guys, Congratulations on completing the project. Everything looks perfect. 🚀 There is nothing to say 😃 Cheers,

Hello, @Ewoskyx 👋 
Thank you for the feedback.
